apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: grafana-tls
  labels:
    app.kubernetes.io/component: grafana
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: openshift-monitoring
    app.kubernetes.io/version: 7.5.5
  name: grafana
  namespace: openshift-monitoring
spec:
  ports:
  - name: https
    port: 3000
    targetPort: https
  - name: metrics
    port: 3002
    targetPort: metrics
  selector:
    app.kubernetes.io/component: grafana
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: openshift-monitoring
  type: ClusterIP
