apiVersion: v1
data:
  ca-bundle.crt: ""
kind: ConfigMap
metadata:
  labels:
    config.openshift.io/inject-trusted-cabundle: "true"
  name: grafana-trusted-ca-bundle
  namespace: openshift-monitoring
