apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: openshift-system-critical
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
value: 1000001000
globalDefault: false
description: "This priority class should be used for addon system facing OpenShift workload pods only. Currently used by monitoring components"
