apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    include.release.openshift.io/hypershift: "true"
    include.release.openshift.io/ibm-cloud-managed: "true"
  labels:
    app: cluster-monitoring-operator
    app.kubernetes.io/managed-by: cluster-version-operator
    app.kubernetes.io/name: cluster-monitoring-operator
    app.kubernetes.io/part-of: openshift-monitoring
  name: cluster-monitoring-operator
  namespace: openshift-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cluster-monitoring-operator
  template:
    metadata:
      annotations:
        target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
      labels:
        app: cluster-monitoring-operator
        app.kubernetes.io/name: cluster-monitoring-operator
    spec:
      containers:
      - args:
        - -namespace=openshift-monitoring
        - -namespace-user-workload=openshift-user-workload-monitoring
        - -configmap=cluster-monitoring-config
        - -release-version=$(RELEASE_VERSION)
        - -logtostderr=true
        - -v=2
        - -cert-file=/etc/tls/private/tls.crt
        - -key-file=/etc/tls/private/tls.key
        - -images=prometheus-operator=quay.io/openshift/origin-prometheus-operator:latest
        - -images=prometheus-config-reloader=quay.io/openshift/origin-prometheus-config-reloader:latest
        - -images=prometheus-operator-admission-webhook=quay.io/openshift/origin-prometheus-operator-admission-webhook:latest
        - -images=configmap-reloader=quay.io/openshift/origin-configmap-reloader:latest
        - -images=prometheus=quay.io/openshift/origin-prometheus:latest
        - -images=alertmanager=quay.io/openshift/origin-prometheus-alertmanager:latest
        - -images=oauth-proxy=quay.io/openshift/origin-oauth-proxy:latest
        - -images=node-exporter=quay.io/openshift/origin-prometheus-node-exporter:latest
        - -images=kube-state-metrics=quay.io/openshift/origin-kube-state-metrics:latest
        - -images=openshift-state-metrics=quay.io/openshift/origin-openshift-state-metrics:latest
        - -images=kube-rbac-proxy=quay.io/openshift/origin-kube-rbac-proxy:latest
        - -images=telemeter-client=quay.io/openshift/origin-telemeter:latest
        - -images=prom-label-proxy=quay.io/openshift/origin-prom-label-proxy:latest
        - -images=k8s-prometheus-adapter=quay.io/openshift/origin-k8s-prometheus-adapter:latest
        - -images=thanos=quay.io/openshift/origin-thanos:latest
        - -images=monitoring-plugin=quay.io/openshift/origin-monitoring-plugin:latest
        - -images=kube-metrics-server=quay.io/openshift/origin-kube-metrics-server:latest
        env:
        - name: RELEASE_VERSION
          value: 0.0.1-snapshot
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: quay.io/openshift/origin-cluster-monitoring-operator:latest
        name: cluster-monitoring-operator
        ports:
        - containerPort: 8443
          name: https
        resources:
          requests:
            cpu: 10m
            memory: 75Mi
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - mountPath: /etc/tls/private
          name: cluster-monitoring-operator-tls
          readOnly: true
        - mountPath: /etc/cluster-monitoring-operator/telemetry
          name: telemetry-config
          readOnly: true
      nodeSelector:
        kubernetes.io/os: linux
      priorityClassName: system-cluster-critical
      serviceAccountName: cluster-monitoring-operator
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/memory-pressure
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      - effect: NoExecute
        key: node.kubernetes.io/unreachable
        operator: Exists
        tolerationSeconds: 120
      - effect: NoExecute
        key: node.kubernetes.io/not-ready
        operator: Exists
        tolerationSeconds: 120
      volumes:
      - configMap:
          name: telemetry-config
        name: telemetry-config
      - name: cluster-monitoring-operator-tls
        secret:
          secretName: cluster-monitoring-operator-tls
