apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: prometheus-operator
    app.kubernetes.io/version: v0.34.1
  name: prometheus-user-workload-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-user-workload-operator
subjects:
- kind: ServiceAccount
  name: prometheus-operator
  namespace: openshift-user-workload-monitoring
